version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: credit_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Arun@3030
    ports:
      - "5432:5432"

  celery:
    build: .
    command: celery -A credit_system worker --loglevel=info
    depends_on:
      - web
